"""
Random number tests using an LCG:

1) Kth sample moment:
   - For each N in N_list, compute:
         M_k(N) = (1/N) * sum_{i=1..N} U_i^k
   - Numerical convergence:
         error_N = |M_k(N) - M_k(N_prev)| (no true value used).
   - Writes 'moment_k.dat'.

2) Autocorrelation (lag = 1):
   - For each N in N_list, compute sample lag-1 autocorrelation:
         rho_1(N) = C_1 / C_0
     where
         C_0 = (1/N) sum (U_i - mean)^2
         C_1 = (1/(N-1)) sum (U_i - mean)(U_{i+1} - mean)
   - Numerical convergence:
         error_N = |rho_1(N) - rho_1(N_prev)|.
   - Writes 'autocorr_lag1.dat'.

3) Kolmogorov–Smirnov test against Uniform(0,1):
   - Generates N_KS samples, sorts them, computes empirical CDF:
         F_n(U_(i)) = i / N_KS
     and D-statistic:
         D = max_i |F_n(U_(i)) - U_(i)|
   - Writes 'ks_uniform.dat' with sorted samples and CDF.
   - Prints D. (Comparison to critical values can be done externally.)

All random numbers are generated by a local LCG (no numpy/random).

How to use in the exam:
- Edit USER PARAMETERS:
      k_for_moment, N_list_moment, N_list_autocorr, N_KS.
- Run:
      python3 mc_tests_moment_autocorr_ks.py
- Gnuplot examples:
      plot 'moment_k.dat'     using 1:3 with linespoints title 'M_k(N)'
      plot 'moment_k.dat'     using 1:4 with linespoints title 'error'
      plot 'autocorr_lag1.dat' using 1:3 with linespoints title 'rho_1(N)'
"""

import math

try:
    import matplotlib.pyplot as plt
    HAVE_MPL = True
except ImportError:
    HAVE_MPL = False

# ========== USER PARAMETERS: CHANGE THESE IN THE EXAM ==========
# LCG parameters
seed = 12345
a    = 1103515245
c    = 12345
m    = 2**31 - 1

# kth moment test
k_for_moment   = 2               # e.g., k=1 for mean, k=2 for second moment
N_list_moment  = [100, 500, 1000, 5000]
moment_file    = "moment_k.dat"

# autocorrelation test (lag 1)
N_list_autocorr = [100, 500, 1000, 5000]
autocorr_file   = "autocorr_lag1.dat"

# Kolmogorov–Smirnov test
N_KS        = 1000
ks_file     = "ks_uniform.dat"
# ===============================================================


class LCG:
    def __init__(self, seed, a, c, m):
        self.X = seed
        self.a = a
        self.c = c
        self.m = m

    def rand(self):
        self.X = (self.a * self.X + self.c) % self.m
        return self.X / float(self.m)


def kth_moment_test():
    rng = LCG(seed, a, c, m)
    prev_M = None

    with open(moment_file, "w") as f:
        f.write("# kth moment test for Uniform(0,1) LCG\n")
        f.write("# col1: N\n")
        f.write("# col2: k\n")
        f.write("# col3: M_k(N) = (1/N)*sum U_i^k\n")
        f.write("# col4: error_N = |M_k(N) - M_k(prev N)|\n")

        N_values = []
        M_values = []
        E_values = []

        for N in N_list_moment:
            s = 0.0
            for _ in range(N):
                u = rng.rand()
                s += u ** k_for_moment
            M_k = s / float(N)

            if prev_M is None:
                error = 0.0
            else:
                error = abs(M_k - prev_M)

            f.write(f"{N} {k_for_moment} {M_k} {error}\n")

            N_values.append(N)
            M_values.append(M_k)
            E_values.append(error)

            prev_M = M_k

    # optional plot
    if HAVE_MPL:
        plt.figure()
        plt.plot(N_values, M_values, marker='o')
        plt.xlabel("N")
        plt.ylabel(f"M_{k_for_moment}(N)")
        plt.title("kth moment vs N")

        eps = 1e-16
        E_no_zero = [e if e > 0.0 else eps for e in E_values]
        plt.figure()
        plt.semilogy(N_values[1:], E_no_zero[1:], marker='o')
        plt.xlabel("N")
        plt.ylabel("|M_k(N) - M_k(prev)|")
        plt.title("kth moment: numerical convergence")
        plt.show()


def autocorr_lag1_test():
    rng = LCG(seed + 999, a, c, m)  # different seed to decouple from moment test
    prev_rho = None

    with open(autocorr_file, "w") as f:
        f.write("# lag-1 autocorrelation test for LCG\n")
        f.write("# col1: N\n")
        f.write("# col2: lag (always 1)\n")
        f.write("# col3: rho_1(N)\n")
        f.write("# col4: error_N = |rho_1(N) - rho_1(prev N)|\n")

        N_values = []
        R_values = []
        E_values = []

        for N in N_list_autocorr:
            if N < 3:
                continue

            data = [rng.rand() for _ in range(N)]
            mean = sum(data) / float(N)

            # C0 (variance-like)
            C0 = 0.0
            for i in range(N):
                C0 += (data[i] - mean) ** 2
            C0 /= float(N)

            # C1 (lag-1 covariance)
            C1 = 0.0
            for i in range(N - 1):
                C1 += (data[i] - mean) * (data[i + 1] - mean)
            C1 /= float(N - 1)

            if abs(C0) < 1e-14:
                rho1 = 0.0
            else:
                rho1 = C1 / C0

            if prev_rho is None:
                error = 0.0
            else:
                error = abs(rho1 - prev_rho)

            f.write(f"{N} 1 {rho1} {error}\n")

            N_values.append(N)
            R_values.append(rho1)
            E_values.append(error)

            prev_rho = rho1

    if HAVE_MPL:
        plt.figure()
        plt.plot(N_values, R_values, marker='o')
        plt.xlabel("N")
        plt.ylabel("rho_1(N)")
        plt.title("Lag-1 autocorrelation vs N")

        eps = 1e-16
        E_no_zero = [e if e > 0.0 else eps for e in E_values]
        plt.figure()
        plt.semilogy(N_values[1:], E_no_zero[1:], marker='o')
        plt.xlabel("N")
        plt.ylabel("|rho_1(N) - rho_1(prev)|")
        plt.title("Autocorrelation: numerical convergence")
        plt.show()


def ks_test_uniform():
    rng = LCG(seed + 2025, a, c, m)
    samples = [rng.rand() for _ in range(N_KS)]
    samples.sort()

    D = 0.0
    with open(ks_file, "w") as f:
        f.write("# KS test data for Uniform(0,1)\n")
        f.write("# col1: i (1..N)\n")
        f.write("# col2: U_(i) (sorted samples)\n")
        f.write("# col3: F_n(U_(i)) = i/N\n")
        f.write("# col4: |F_n(U_(i)) - U_(i)|\n")

        for i, u in enumerate(samples, start=1):
            F_emp = i / float(N_KS)
            diff = abs(F_emp - u)
            if diff > D:
                D = diff
            f.write(f"{i} {u} {F_emp} {diff}\n")

    print("KS test against Uniform(0,1):")
    print("  N =", N_KS)
    print("  D-statistic =", D)
    print("  (Compare D with critical values externally if needed.)")
    print("KS data written to:", ks_file)

    if HAVE_MPL:
        # Plot empirical CDF vs x (simple stairs-like scatter)
        xs = [s for s in samples]
        Fs = [i / float(N_KS) for i in range(1, N_KS + 1)]
        plt.figure()
        plt.plot(xs, Fs, marker='.', linestyle='none')
        plt.xlabel("x")
        plt.ylabel("F_n(x)")
        plt.title("Empirical CDF from LCG samples")
        plt.show()


def main():
    kth_moment_test()
    autocorr_lag1_test()
    ks_test_uniform()


if __name__ == "__main__":
    main()